scrape_configs:
  - job_name: "kiran-youtube-app"
    metrics_path: /actuator/prometheus
    scheme: http
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - default
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: kiran-youtube-app
      - source_labels: [__meta_kubernetes_endpoint_port_number]
        action: keep
        regex: 8082

